
on:
  pull_request:
  merge_group:
  push:
    branches: [main]

name: Check

jobs:
  license-check:
    runs-on: coln-runner
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Check licenses
        run: just check-licenses
  rust-fmt:
    runs-on: coln-runner
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Check formatting
        run: cargo fmt --check

  rust-clippy:
    runs-on: coln-runner
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

  rust-tests:
    runs-on: coln-runner
    # needs: [rust-fmt, rust-clippy]
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Run tests
        run: cargo test

  coln-js-runtime-check:
    runs-on: coln-runner
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install npm dependencies
        working-directory: packages/coln-js-runtime
        run: pnpm ci

      - name: Rust Checks
        working-directory: packages/coln-js-runtime
        run: just test-rust

      - name: JS Checks
        working-directory: packages/coln-js-runtime
        run: just test-npm

  haskell-tests:
    runs-on: coln-runner

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      # - name: Set up Cachix ♻️
      #   uses: cachix/cachix-action@v17
      #   with:
      #     name: coln
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Formatting (.hs)
        run: nix build .#format-hs

      - name: Formatting (.cabal)
        run: nix build .#format-cabal

      - name: Haskell Tests
        run: |
          RUN_CHECKS=$(nix build .#haskell-tests --no-link --print-out-paths)
          $RUN_CHECKS
