on:
  push:
    branches:
      - main

name: Deploy

jobs:
  deploy-manual:
    runs-on: coln-runner

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      # - name: Set up Cachix ♻️
      #   uses: cachix/cachix-action@v17
      #   with:
      #     name: coln
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build manual
        run: nix build .#manual

      # - name: Deploy manual
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     deploy_key: ${{ secrets.COLN_WEBSITE_DEPLOY_KEY }}
      #     external_repository: coln-project/coln-project.github.io
      #     publish_branch: main
      #     publish_dir: ./result
